# Ultralytics 🚀 AGPL-3.0 许可证 - https://ultralytics.com/license

# Ultralytics 解决方案的全局配置 YAML，包含设置和参数
# 文档请参考 https://docs.ultralytics.com/solutions/

# 物体计数设置  --------------------------------------------------------------------------------------------
region: # list[tuple[int, int]] 物体计数、排队或速度估算的区域坐标点。
show_in: True # (bool) 是否显示进入定义区域的物体
show_out: True # (bool) 是否显示离开定义区域的物体

# 热力图设置  ----------------------------------------------------------------------------------------------------
colormap: # (int | str) 热力图的颜色映射，仅支持 OPENCV 提供的颜色映射。

# 健身监测设置  -----------------------------------------------------------------------------------------
up_angle: 145.0 # (float) 运动上升角度，默认值为 145.0。
down_angle: 90 # (float) 运动下降角度，默认值为 90。
kpts: [6, 8, 10] # (list[int]) 用于健身监测的关键点索引，例如俯卧撑监测使用 [6, 8, 10] 关键点。

# 数据分析设置  ---------------------------------------------------------------------------------------------------
analytics_type: "line" # (str) 统计分析的图表类型，如 "line"（折线图）、"pie"（饼图）、"bar"（柱状图）或 "area"（面积图）。
json_file: # (str) 停车系统区域的 JSON 文件路径。

# 安防报警系统设置  ---------------------------------------------------------------------------------------
records: 5 # (int) 触发安全报警的检测次数阈值，当达到该次数时发送邮件通知。
